# Generated by Django 3.2.7 on 2021-09-07 11:09

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_auto_20210907_1058'),
    ]

    operations = [
        migrations.AddField(
            model_name='stay',
            name='visits',
            field=django.contrib.gis.db.models.fields.MultiPointField(blank=True, null=True, srid=4326, verbose_name='Lieux visités'),
        ),
        migrations.AlterField(
            model_name='stay',
            name='date_visited',
            field=models.DateField(blank=True, verbose_name='Date de dernière visite'),
        ),
    ]
